schema: '2'
goal: Snapshot of maid_runner/cli/commands/files.py
type: snapshot
files:
  snapshot:
  - path: maid_runner/cli/commands/files.py
    artifacts:
    - kind: function
      name: cmd_files
      args:
      - name: args
        type: argparse.Namespace
      returns: int
    - kind: function
      name: cmd_manifests
      args:
      - name: args
        type: argparse.Namespace
      returns: int
validate:
- pytest tests/ -v
created: '2026-04-03T04:41:51.145222+00:00'
