schema: '2'
goal: Snapshot of maid_runner/cli/commands/manifest.py
type: snapshot
files:
  snapshot:
  - path: maid_runner/cli/commands/manifest.py
    artifacts:
    - kind: function
      name: cmd_manifest
      args:
      - name: args
        type: argparse.Namespace
      returns: int
validate:
- pytest tests/ -v
created: '2026-04-03T04:41:52.100377+00:00'
