schema: '2'
goal: Snapshot of maid_runner/core/test_runner.py
type: snapshot
files:
  snapshot:
  - path: maid_runner/core/test_runner.py
    artifacts:
    - kind: function
      name: run_command
      args:
      - name: command
        type: tuple[str, Ellipsis]
      returns: TestRunResult
    - kind: function
      name: run_manifest_tests
      args:
      - name: manifest_path
        type: Union[str, Path]
      returns: BatchTestResult
    - kind: function
      name: run_tests
      args:
      - name: manifest_dir
        type: Union[str, Path]
        default: '''manifests/'''
      returns: BatchTestResult
validate:
- pytest tests/ -v
created: '2026-03-26T05:46:09.968143+00:00'
