"""Graph module for the Knowledge Graph Builder.

This module provides data structures for representing the MAID codebase
as a knowledge graph with nodes and edges.
"""

from maid_runner.graph.model import (
    NodeType,
    Node,
    ManifestNode,
    FileNode,
    ArtifactNode,
    ModuleNode,
    EdgeType,
    Edge,
    KnowledgeGraph,
    MANIFEST_PREFIX,
    FILE_PREFIX,
    ARTIFACT_PREFIX,
    MODULE_PREFIX,
    EDGE_PREFIX,
)
from maid_runner.graph.exporters import (
    export_json,
    export_dot,
    export_graphml,
    graph_to_dict,
    graph_to_dot,
    graph_to_graphml,
)
from maid_runner.graph.query import (
    find_nodes_by_type,
    find_node_by_name,
    get_neighbors,
    find_dependents,
    find_dependencies,
    get_dependency_tree,
    find_cycles,
    is_acyclic,
    get_affected_files,
    get_affected_manifests,
    analyze_impact,
    QueryType,
    QueryIntent,
    QueryParser,
    QueryResult,
    QueryExecutor,
)
from maid_runner.graph.builder import GraphBuilder
from maid_runner.graph.query import GraphQuery

__all__ = [
    "NodeType",
    "Node",
    "ManifestNode",
    "FileNode",
    "ArtifactNode",
    "ModuleNode",
    "EdgeType",
    "Edge",
    "KnowledgeGraph",
    "MANIFEST_PREFIX",
    "FILE_PREFIX",
    "ARTIFACT_PREFIX",
    "MODULE_PREFIX",
    "EDGE_PREFIX",
    "export_json",
    "export_dot",
    "export_graphml",
    "graph_to_dict",
    "graph_to_dot",
    "graph_to_graphml",
    "find_nodes_by_type",
    "find_node_by_name",
    "get_neighbors",
    "find_dependents",
    "find_dependencies",
    "get_dependency_tree",
    "find_cycles",
    "is_acyclic",
    "get_affected_files",
    "get_affected_manifests",
    "analyze_impact",
    "QueryType",
    "QueryIntent",
    "QueryParser",
    "QueryResult",
    "QueryExecutor",
    "GraphBuilder",
    "GraphQuery",
]
